import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black overflow-auto`}>
        {children}
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.4/p5.js"
          integrity="sha512-pdHIQH5GDrd5eTHck+rfKnQhgRjKYtSw8UCQ9blobxwzQhE9LXLw5aTk78ktWY526mS0EwIcaJ/fROeIzHD34w=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        ></script>
      </body>
    </html>
  );
}
